[out:json][timeout:150];
(
  relation["type"="route"]["state"="construction"](39.55,32.30,40.35,33.35);
  relation["type"="route"]["state"="construction"](38.20,26.60,38.80,27.60);
  relation["type"="route"]["state"="construction"](40.05,28.70,40.40,29.50);
  relation["type"="route"]["state"="construction"](36.70,30.30,37.15,31.10);
  relation["type"="route"]["name"~"Buca|yapım|inşa|construction|proje",i](38.20,26.60,38.80,27.60);
  relation["type"="route"]["name"~"yapım|inşa|construction|proje",i](40.05,28.70,40.40,29.50);
  relation["type"="route"]["name"~"yapım|inşa|construction|proje",i](36.70,30.30,37.15,31.10);
  relation(17289371);
);
out tags;
