[out:json][timeout:150];
(
  relation["construction:route"~"subway|light_rail|tram"](39.55,32.30,40.35,33.35);
  relation["proposed:route"~"subway|light_rail|tram"](39.55,32.30,40.35,33.35);
  relation["construction:route"~"subway|light_rail|tram"](38.20,26.60,38.80,27.60);
  relation["proposed:route"~"subway|light_rail|tram"](38.20,26.60,38.80,27.60);
  relation["construction:route"~"subway|light_rail|tram"](40.05,28.70,40.40,29.50);
  relation["proposed:route"~"subway|light_rail|tram"](40.05,28.70,40.40,29.50);
  relation["construction:route"~"subway|light_rail|tram"](36.70,30.30,37.15,31.10);
  relation["proposed:route"~"subway|light_rail|tram"](36.70,30.30,37.15,31.10);
  relation(19925415);
);
out tags;
